#Copy the hammer configuration from template to the .hammer directory
- name: "Email | set email configuration"
  template:
    src: "email.yaml.j2"
    dest: "/etc/foreman/email.yaml"
  notify: "restart katello service"
  tags: email

- name: "Email | set email reply address"
  shell: "HOME=/root hammer settings set 
    --name email_reply_address
    --value {{ satellite_deployment_email_address }}"
  tags: email

- name: "Email | set admin email address"
  shell: "HOME=/root hammer settings set
    --name administrator
    --value {{ satellite_deployment_administrator_email }}"
  tags: email
